version: '3.9'

services:
  db:
    image: postgres:15.3
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c "sleep 5 && aerich upgrade && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: jaeger
    ports:
      - "16686:16686"   
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14250:14250"
      - "4317:4317" 
      - "4318:4318"  
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  postgres_data:
